### ISSUE TITLE
 32-bit node ID problem?

### ISSUE THREAD

**Issue by nrenner** [davidchiles/osm-poi-editor-iOS#1]
I stumbled upon [changeset 14990834](http://www.openstreetmap.org/browse/changeset/14990834) that was created by OSMPOIEditor and updated 

[node 2147483647](http://www.openstreetmap.org/browse/node/2147483647) (2^31 - 1 !), which was part of [way 204773635](http://www.openstreetmap.org/browse/way/204773635),
instead of 
[node 2150004875](http://www.openstreetmap.org/browse/node/2150004875)

This looks like being related to node identifiers exceeding the 32-bit signed integer space, see http://wiki.openstreetmap.org/wiki/64-bit_Identifiers.

Can you please confirm receiving this issue as soon as you read it, so I know that you are aware of the problem.

**Comment by nrenner** [comment]
There is another node update that apparently failed (empty, no changes):
Update http://www.openstreetmap.org/browse/changeset/14991421
Create: http://www.openstreetmap.org/browse/changeset/14991384

**Comment by davidchiles** [comment]
Fixed c2991fef0412fc9428a8483fff1eb081bee5a6e1
Waiting for app aproval
